# Spring 相关配置
spring:
  # 配置应用信息
  application:
    # 配置应用名称
    name: spring-ai-demo

  # Spring AI 相关配置
  ai:
    # openai 配置
    openai:
      # 配置使用的 大模型 API KEY , 当前是使用已配置好的系统环境变量 DASHSCOPE_OPEN_AI_API_KEY 值, 注意, 当配置好环境变量时需要重启电脑才能生效
      api-key: ${DASHSCOPE_OPEN_AI_API_KEY}
      # 配置使用大模型的 Base URL 地址, 在对应 大模型的 官方文档中存在
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      # 配置大模型 chat client 参数
      chat:
        # 配置需要调用的 大模型 名称, 在对应 大模型的 官方文档中存在
        model: ${OPENAI_LLM_MODEL:qwen3.7-plus}
        # 配置大模型 chat 超时时间
        timeout: 120s
      # 配置 嵌入式 参数
      embedding:
        # 配置 嵌入式 模型参数, 在对应 大模型的 官方文档中存在
        model: ${EMBEDDING_LLM_MODEL:text-embedding-v4}
        # 配置 嵌入式 模型的向量维度
        dimensions: 2048
    # 本地 Ollama 配置 (需要在本地部署 Ollama)
    ollama:
      # 配置 本地部署的 Ollama 的地址, 因为是在本机, 故使用如下地址, 如果部署在局域网内,只需要把 localhost 替换为对应的局域网地址
      base-url: http://localhost:11434
      # 配置 Ollama 的 chat client 参数
      chat:
        # 配置本地安装的 大模型 名称, 在对应的 Ollama 官方的 Model 中存在
        model: ${OLLAMA_LLM_MODEL:deepseek-r1:1.5b}
    # 模型配置
    model:
      # 配置嵌入式模型, 使用 OpenAI 进行模型调用
      embedding: openai
    # 向量存储配置
    vectorstore:
      # 使用 Redis 进行向量存储
      redis:
        # 是否在启动时创建/初始化向量索引等结构
        initialize-schema: true
        # RedisSearch 里的 索引名
        index-name: ranyk_index
        # 存向量文档用的 Redis 键前缀
        prefix: ranyk_vector_

  # 数据源配置
  data:
    # 配置 Redis 数据源
    redis:
      # 配置 Redis 客户端类型
      client-type: jedis
      # 配置 Redis 服务器地址
      host: 192.168.31.83
      # 配置 Redis 服务器端口
      port: 16380
      # 配置使用 Redis 的那个数据库 (在 Redis Stack 向量数据库时, 好像无法生效, 所有的向量存储均存放在 0 号数据库)
      database: 0
      # 配置 Jedis 参数
      jedis:
        # 配置 Jedis 连接池参数
        pool:
          # 配置是否启用 Jedis 连接池
          enabled: false

  # 配置 Web 相关参数
  web:
    # 配置 Web 本地化参数
    locale: zh_CN
    # 配置 Web 本地化解析器
    locale-resolver: accept-header

  # 文件上传配置
  servlet:
    multipart:
      # 单个文件最大大小
      max-file-size: 50MB
      # 整个请求最大大小
      max-request-size: 200MB
      # 文件大小阈值，超过此值会写入临时文件
      file-size-threshold: 2KB


# 日志配置
logging:
  # 配置日志级别
  level:
    # 配置 Spring AI 的日志级别为 debug
    org.springframework.ai: debug
    # 配置项目日志级别为 debug
    com.ranyk.spring.ai.demo: debug

# 自定义配置 - 向量配置
vector:
  # 自定义配置 - 向量数据配置
  vector-data:
    # 自定义配置 - 向量数据删除配置
    delete:
      # 自定义配置 - 向量数据删除每批次数量
      batch-quantity: 100

# 自定义配置
file:
  # 自定义配置 - 文件上传配置
  upload:
    # 自定义配置 - 文件上传根目录: ${user.dir} 如果是 IDEA 则为当前项目所在根目录; 如果是 Jar 包则为当前执行 java -jar 时的目录
    root: ${user.dir}/upload

# 服务器配置
server:
  # 配置服务器端口
  port: 8080